name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Fibonacci
      run: cd fibonacci && cargo build --verbose
    - name: Run tests Fibonacci
      run: cd fibonacci && cargo test --verbose
    - name: Build Rocket Rest
      run: cd rocket-rest && cargo build --verbose
    - name: Run tests Rocket Rest
      run: cd rocket-rest && cargo test --verbose
